### ISSUE TITLE
Searching for an attribute in a many to many relationship

### ISSUE THREAD

**Issue by disvst** [OFFLINE-GmbH/oc-site-search-plugin#100]
hello, I'm trying to display results (articles in my case) with tags whose name would match the search, but I get an error. I did not find any answer or help about this, would you please help?  

###  
            $items = Models\Article
                ::active()
                ->where('title', 'like', "%${query}%")
                ->orWhere('content', 'like', "%${query}%")
                ->orWhere('type', 'like', "%${query}%")
                ->orWhere('tags', function ($query) {
                    $query->where('name', 'like', '%${query}%');
                })
                ->get();

**Comment by tobias-kuendig** [comment]
Maybe you should post the error as well.

**Comment by disvst** [comment]
Of course, here is the error 

Object of class October\Rain\Database\QueryBuilder could not be converted to string

**Comment by tobias-kuendig** [comment]
the whole thing around it (line, stack trace) is important too!
