### ISSUE TITLE
Error "Call to a member function slice() on null"

### ISSUE THREAD

**Issue by Tciferblatt** [OFFLINE-GmbH/oc-site-search-plugin#102]
Hi,
Build 469
OFFLINE MALL
OFFLINE site-search-plugin

After search submit result page give me an error:

    Call to a member function slice() on null
    /xxx/public_html/plugins/offline/sitesearch/components/SearchResults.php line 212

    Exception
    Symfony\Component\Debug\Exception\FatalThrowableError

    line 212  return $results->slice(($this->pageNumber - 1) * $this->resultsPerPage, $this->resultsPerPage);

Any ideas how to fix this problem?
P.S. Also "search on type/live search" doesn't work - no results :((

Thank you in advance

**Comment by tobias-kuendig** [comment]
By the looks of it, this line returns `null`:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/components/SearchResults.php#L170

Do you have an `offline.sitesearch.results` event listener registered that returns empty results?

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/33b47d278f23bebde8d99af402c16d5abe2eaa38/classes/SearchService.php#L77

Following the default code path, even if no results are returned, you should still end up with an empty `Collection` instance, but never `null` except if a event listener returns null explicitly.

We could handle this case better, but it is interesting where the null value comes from anyway.

**Comment by tobias-kuendig** [comment]
Fixed in 926f8f8
