### ISSUE TITLE
Fix Exception for bad pageNumber parameter

### ISSUE THREAD

**Issue by bob-tm** [OFFLINE-GmbH/oc-site-search-plugin#103]
Hi. 

This kind of query will crash search. A lot of bots generate them.

/search/?page=22%27%29%20AND%209526%3D6581%20AND%20%28%27Cnri%27%3D%27Cnri&q=BlaBlaBLa

Problem in file plugins/offline/sitesearch/components/SearchResults.php

add something like this:

```
	$pageNumber = Request::get('page', 1);
	if (!is_int($pageNumber))
		$pageNumber = 1;
		
        $this->setVar('pageNumber', $pageNumber);
```

tnx!

**Comment by tobias-kuendig** [comment]
Fixed in 25ee37bda32cc9e8aa8b9718c958e33afc57726d, thanks!
