### ISSUE TITLE
[searchResult] inject `en` in the search result link

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-site-search-plugin#114]
Using it with only the provider `Indikator.News`.

The link is injected with `en` which I am not using in my website.

example:
`mydomain.com/en/news/improve-your-customer-experience-2022-08-12-09-41-42`

and the correct URL is
`mydomain.com/news/improve-your-customer-experience-2022-08-12-09-41-42`

**Comment by dathwa** [comment]
I'm seeing this on OCMS v2.2.35, sitesearch v1.7.5 with StaticPages plugin. Any way we can lose the "en" slug?

**Comment by tobias-kuendig** [comment]
The problem is probably around here: https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/6fce4d8dd9beb3ae41e228b1533250bc8af2a6d4/classes/providers/IndikatorNewsResultsProvider.php#L84

**Comment by dathwa** [comment]
Aah, yes. That function is also in [RainlabPagesResultsProvider](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/6fce4d8dd9beb3ae41e228b1533250bc8af2a6d4/classes/providers/RainlabPagesResultsProvider.php).
I tried removing the translate plugin, but it's required by MALL...
```
>composer why rainlab/translate-plugin
offline/oc-mall-plugin  v2.0.21  requires  rainlab/translate-plugin (^1.9.0)
```
Any suggestions, @tobias-kuendig ?

**Comment by tobias-kuendig** [comment]
Please check version `v1.7.8` and see if the problem still exists. Thank you!

Ref 28ebab9

**Comment by dathwa** [comment]
> Please check version `v1.7.8` and see if the problem still exists. Thank you!
> 
> Ref [28ebab9](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/28ebab96f282e6ba5740212e18c2c557730de9c4)

I had too many composer conflicts in my ocms2, so I ended up updating to ocms3. Problem is fixed here: Thanks @tobias-kuendig
