### ISSUE TITLE
Thumbnails Broken After Refactor

### ISSUE THREAD

**Issue by billyzduke** [OFFLINE-GmbH/oc-site-search-plugin#12]
Hi there

Attempting to integrate your re-factored version of the Octoshop-capable search on my end, I noticed a couple problems with the thumbnails returned with results...

Firstly, I was getting an error in the Result.php class, line 157, where you type hint the attribute as "File." The Octoshop provider seems to provide an empty stdClass object when there is no thumb, but I'm guessing this hasn't been worked into the remaining providers yet, as the error was "received null, type File expected."

When I resolved that (just by removing the type hint to see how the results looked) I saw in my results list something I'd seen early on during my own development: all the thumbnails for a big list of different results were displaying the same image.

Keep up the good work, this is an invaluable plugin for OctoberCMS!

**Comment by tobias-kuendig** [comment]
Could you try to replace the current octoshop provider with this patched one? 
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/bugfix/issue-12/classes/providers/FeeglewebOctoshopProductsResultsProvider.php

I don't want to remove the type hint to make sure only `System\Models\File` instances are passed as thumbnail. This makes the handling in the view much more consistent and easier.

> The Octoshop provider seems to provide an empty stdClass object when there is no thumb

Even if there are no thumbnails available, there should be returned an empty Collection, no stdClass.

> all the thumbnails for a big list of different results were displaying the same image.

Could you show me your component view code? Have you tried temporarily replacing it with the original from the plugin? Does this problem still occur?

Thanks!

**Comment by tobias-kuendig** [comment]
@billyzduke, did you find some time to look at this issue by any chance?

Thanks!

**Comment by billyzduke** [comment]
Hi Tobias

Sorry, I haven't had time to check it out yet, been involved in extensive
(and extremely frustrating) Rainlab.User Account component extension for
same project... Another project vying for attention as well soon. I froze
updates on Sitesearch for the current project and left it with the version
that I sent you as pull request. It will probably be a while before I get
back to it... But I will probably have a Rainlab Forum search provider for
you when I do return.



[image:   Billy Z Duke about.me/billyzduke]
[image: --]
Billy Z Duke
[image: http://]about.me/billyzduke
<http://about.me/billyzduke>

**Comment by Dimsanchuk** [comment]
I have same problem with RainLab.Blog. Error occurred in Result.php, line 157: "setThumb() must be an instance of System\Models\File, null given". Blog post has no featured images.

**Comment by tobias-kuendig** [comment]
This problem should be resolved in version 1.2.4
