### ISSUE TITLE
Many problems related to Tailor search

### ISSUE THREAD

**Issue by PubliAlex** [OFFLINE-GmbH/oc-site-search-plugin#132]
Hello,

I firstly created some issues related to search in tailor model, but I encoutered many issues so I prefer to resume them all in that post.

### First issue, can't use pageName and urlParams.
When you use pageName and urlParams to define the links of your tailor model, the searchResult page display an error : 

`str_starts_with(): Argument #1 ($haystack) must be of type string, array given`

You have to use the resolveSiteSearchUrl() method to make it works.

### Second issue, the model is not attached to the result object

Here is a screenshot of a result object : 
![image](https://user-images.githubusercontent.com/55833027/230334313-0363a02f-6782-409b-a830-967fa3a130cc.png)

As you can see, the model is not attached to the result, which prevent any form of customization. For example, I can't display the image of the model as I can only access the title, text, and url attributes

**Comment by tobias-kuendig** [comment]
Thank you for this report @PubliAlex.

## First issue

The example in the README was wrong, you have to define the params as a dictionary, not as an array, see:
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/e81ab4ac181a010df8082368a18a60228f9399fa

## Second issue

The model is now set for each Tailor search result starting from v1.7.4.
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/4f3512f631f6c336d7c036d224317ddf31994c21

**Comment by PubliAlex** [comment]
Thank you @tobias-kuendig, premium support, as always
