### ISSUE TITLE
If was modify the query string before searching to empty - error 500 or searching original string

### ISSUE THREAD

**Issue by artcifra** [OFFLINE-GmbH/oc-site-search-plugin#133]
Use this instruction [https://github.com/OFFLINE-GmbH/oc-site-search-plugin#modify-the-query-before-searching
](url)

If I process the search string (remove punctuation and anything shorter than 3 characters) for example:
'Product-233' ->'product 233'
'PUT-2' -> 'put' 
'PU-2' -> " 

the forceQuery() method will not help, because if the this->forced request is empty, it will not override this->query , and if you pass the string " ", there will be an error of 500

If I have an empty string after modification, I cannot interrupt the search or pass an empty string to the component so that the component stops the search itself

The component 'searchInput' component is also rendered on the page  but how to pass the modified string to it is.

**Comment by tobias-kuendig** [comment]
Starting from version `v1.7.10`, your forced query is always used (even if empty).

Ref 1a9f7b3
