### ISSUE TITLE
Thumbs and other fields (meta) in Tailor results fields?

### ISSUE THREAD

**Issue by aminusmin** [OFFLINE-GmbH/oc-site-search-plugin#135]
Hi,

When searching in Tailor, is it possible to also add a thumb and other fields (meta) to the resultsFields? 

Thanks

**Comment by tobias-kuendig** [comment]
Starting from `v1.7.12` you can access all Tailor fields via `result.meta`. There is also a new `thumbFrom` setting that allows you to define the field to use as thumb.

Ref a44f2a4
