### ISSUE TITLE
Wrong result urls using the search plugin with the multisite feature and translate plugin

### ISSUE THREAD

**Issue by pcr-coding** [OFFLINE-GmbH/oc-site-search-plugin#142]
When using the _Multisite feature_ and I define under _Manage Sites_ multiple sites with locale prefixes, like 2 sites

-  `/` (for German)
-  `/en` (for English)

Then my search result urls of the rainlab.pages plugin are wrong and appear like:

- `myproject.localhost/de//test-seite/test-unterseite`
- `myproject.localhost/en//test-page/test-subpage`

containing a double slash `//` after the. Also even that I didn't define a `/de` prefix for German but only `/` (without any prefix) I get the `/de` in my search result urls.

I figured the issue must have to do with the `public function withLocalePrefix($url)` in the `ResultsProvider.php` that creates the url and adds the locale into the url.

I replaced the entire content of that function with `return Cms::url($url);` and it seems to work properly then. Not sure if that's the final solution to the issue, but for now I didn't have any bad effects and the urls show correctly as:

- `myproject.localhost/test-seite/test-unterseite`
- `myproject.localhost/en/test-page/test-subpage`

Can anyone confirm the issue and the solution, or has any better ideas how to solve my issue?

**Comment by tobias-kuendig** [comment]
Thank you for this report! This has been fixed in v1.7.16, let me know if you experience any further problems.
