### ISSUE TITLE
Same pages from boxes plugin show up multiple times

### ISSUE THREAD

**Issue by LeonKercmar** [OFFLINE-GmbH/oc-site-search-plugin#143]
I've noticed that after searching for a certain page the page that is created using the boxes plugin shows up multiple times. Is there a way to display the same page only once? I have revisions enabled in the boxes plugin.

**Comment by tobias-kuendig** [comment]
@LeonKercmar thank you for this report! This was a bug in the Boxes plugin. It is fixed in v3.3.6.
