### ISSUE TITLE
multilingual search not work

### ISSUE THREAD

**Issue by ribsousa** [OFFLINE-GmbH/oc-site-search-plugin#26]
I have a problem!

When I search for a term in Portuguese it works, but when I change the language of the site, for example English and I search for an English term, the search does not return results.

**Multilingual contents via RainLab.Translate are supported?**

**Comment by tobias-kuendig** [comment]
What content types are you searching for?

Ronaldo Ribeiro de Sousa <notifications@github.com> schrieb am Mi., 14.
Dez. 2016, 18:37:

**Comment by ribsousa** [comment]
Blog post
see [site gleebe](http://gleebe.org)

click in navbar search icon for open search!

**Comment by tobias-kuendig** [comment]
Ah yes. The support for multilingual contents via Rainlab.Translate has not been implemented in every search provider yet. 

I have released a new version on the edge updates channel. Could you test if it works correctly now? If you don't want to switch to the edge channel you just have to replace this file:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/master/classes/providers/RainlabBlogResultsProvider.php

**Comment by ribsousa** [comment]
Ok, it's working now!
