### ISSUE TITLE
Add support for autocomplete

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-site-search-plugin#27]

**Comment by ayumihamsaki** [comment]
Hi not sure if this is helpful or not? But why don't you just add typeahead.js to the search form in the plugin..?

See here: https://twitter.github.io/typeahead.js/

**Comment by tobias-kuendig** [comment]
I'd prefer not to ship with a dependency on any of the many autocomplete widgets out there. I think the best solution is to implement a simple json endpoint where the user can fetch results for a query. This way you can use the autocompleter you want or even write one yourself. Maybe we can ship the plugin with a working autocomplete example using the json endpoint implemented with October's own ajax framework.

**Comment by BesoKakulia** [comment]
I have a problem with images. It shows one image for all searched results, can you help me . TY

**Comment by Floriskoch** [comment]
Thanks for the autocomplete example branch! But how would I go about implementing this without touching the core of the plugin?

**Comment by tobias-kuendig** [comment]
I don't think it's possible to implement it without touching the core since the plugin was not programmed with auto complete functionalities in mind. Maybe I'll get around to finish the autocomplete component in the comming days and release it in a new version of the plugin.

So either you'll have to fork the autocomplete branch and merge it later or wait until a new version is released.

**Comment by AugmentBLU** [comment]
Hello,

is there any update on this feature? I think it would be a great addition, I like the idea of it not being tied to a specific autocomplete widget as I am using different frameworks and flexibility is key (if poss).

**Comment by tobias-kuendig** [comment]
This is still a work in progress. I'll release the feature when I (or someone else) came around to finish it. It currently doesn't have the highest priority, though.

**Comment by tobias-kuendig** [comment]
This feature is now available via edge updates in version 1.3.1.

See the [updated README](https://github.com/OFFLINE-GmbH/oc-site-search-plugin#searchinput) for usage instructions.

**Comment by tobias-kuendig** [comment]
Closing this issue since this feature has been available for a while now.
