### ISSUE TITLE
Adding a map service to search

### ISSUE THREAD

**Issue by Michael-Reich** [OFFLINE-GmbH/oc-site-search-plugin#30]
Is it maybe possible to add a map plugin to the search possibilities? 

Like
- Leaf.js
- Google Maps
- Or other

Is that possible?

**Comment by tobias-kuendig** [comment]
What exactly are you trying to do? What contents are you searching?

If you want to display a map beside each search result you can do this yourself by editing the results partial.

**Comment by MichiReich** [comment]
I want to create a form and this should contain a PLZ search which shows possible store locations on the map.

I thought maybe it is possible with sitesearch + a different plugin from the marketplace. (Like [this](https://octobercms.com/plugin/fencus-googlemapswidgets))

**Comment by tobias-kuendig** [comment]
You should be able to achieve this with a custom plugin or a custom search provider. The function of this plugin is to search existing contents, not to manage them. You could build a plugin where you manage your store locations and then extend the SiteSearch plugin's functionality to search for your stores. But it would still search for other contents. You're better off creating the search functionality yourself in this case.
