### ISSUE TITLE
[bug] "Search" finds hidden static pages

### ISSUE THREAD

**Issue by plyusninva** [OFFLINE-GmbH/oc-site-search-plugin#33]
"Search" finds hidden static pages
![image](https://cloud.githubusercontent.com/assets/25381948/24996853/e63e168c-204d-11e7-91bc-6ea5c99a388b.png)

result
![image](https://cloud.githubusercontent.com/assets/25381948/24996882/ff641dbe-204d-11e7-824a-c44a2a7c8e98.png)

**Comment by tobias-kuendig** [comment]
Good catch! Fixed in 1.2.26.

**Comment by plyusninva** [comment]
Thank you very much for a quick solution to the problem
