### ISSUE TITLE
Tell one result type from another in content.htm

### ISSUE THREAD

**Issue by graker** [OFFLINE-GmbH/oc-site-search-plugin#36]
Is there a way to tell one model type from another when rendering partial? For example, I'm thinking of displaying different `visitPageMessage` in `content.htm` depending on whether the item found is a blog post or a photoalbum. Is there something to check result item's model class? Thanks!

**Comment by tobias-kuendig** [comment]
Great idea! [I've added a `result.identifier` property](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/4401362eaeaa76d15d3b948d656ee265eb9aa291) that returns the identifier of the results provider. This way you'll be able to tell which provider has generated your result.

**Comment by graker** [comment]
Brilliant, thank you!
