### ISSUE TITLE
Sorting results by provider type

### ISSUE THREAD

**Issue by Floriskoch** [OFFLINE-GmbH/oc-site-search-plugin#38]
I'm using your plugin to search through cms pages and various types of records of my own plugin. What would be a good way of displaying the search results based on the type of record instead of just having one big list of search results? Thanks in advance!

**Comment by tobias-kuendig** [comment]
If you update to the latest version `1.2.30` you can do something like this on your page:

```php
title = "Search"
url = "/search"

[searchResults]

==
function onEnd() {
    $this['grouped'] = $this->components['searchResults']->resultCollection->groupBy('provider');
}
==

{{ grouped }}
```

You can grab the `resultCollection` variable and use it like any other Laravel collection.
