### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by BesoKakulia** [OFFLINE-GmbH/oc-site-search-plugin#39]
Project model

public $attachOne = [
        'images' => 'System\Models\File'
    ];
/***************************************/

Plugin.php
 'thumb' => $item->images->first(), // Instance of System\Models\File

Every thing work, but not thumb. It returns one image for all searched results.
How can i fix it , Thanks.

**Comment by tobias-kuendig** [comment]
Did you change anything in the html partials?

Can you show me your complete `Plugin.php`?

**Comment by BesoKakulia** [comment]
![image](https://cloud.githubusercontent.com/assets/26166174/26401518/66fb29a4-4097-11e7-8a98-d2a7e2c971f2.png)


        <img class="ss-result__image" src="{{ result.thumb.getThumb(120, auto) }}" alt=""/>

**Comment by tobias-kuendig** [comment]
Does changing line 35 to 

```php
'thumb' => $item->images
```

chance anything? Since you are using an `attachOne` relationship in your model you shouldn't need to call `first()` on the relation to get your image.

**Comment by BesoKakulia** [comment]
Thank you so much, it works perfectly. Great job, great plugin.
