### ISSUE TITLE
multilingual search

### ISSUE THREAD

**Issue by BesoKakulia** [OFFLINE-GmbH/oc-site-search-plugin#40]
I have custom plugins, and i want to search their results. It works on default  language, but it does not works on other languages. What can i do ? I use Rainlab.translate plugin for translation. Thank you.

**Comment by tobias-kuendig** [comment]
You should be able to search the contents in your current locale by using the `transWhere` function instead of `where`.

```php
$results = Item::where('title', $query)...
// becomes
$results = Item::transWhere('title', $query)...
```

Also make sure to define `['index' => true]` on your model's `$translatable` properties to make them searchable via `transWhere` (see https://github.com/rainlab/translate-plugin/blob/8109cbb2c399c2ac2fb7d3bd101eae069930a0c2/README.md#indexed-attributes).

You'll have to look at the RainLab.Translate plugin for details on how to use `transWhere`.

**Comment by BesoKakulia** [comment]
Ok, thank you very much.

**Comment by BesoKakulia** [comment]
$items = Models\Event::transWhere('title', 'like', "%${query}%")
                ->orWhere('description', 'like', "%${query}%")
                ->get();



    public $translatable = [ ['title', 'index' => true], 'description'];

I have this code, but it does not works, what do i do wrong ?

**Comment by tobias-kuendig** [comment]
Hard to say. I'd start by looking at the queries October generates. 

```php
\DB::enableQueryLog();
$items = Models\Event::transWhere('title', 'like', "%${query}%")
->orWhere('description', 'like', "%${query}%")
->get();
dd(\DB::getQueryLog());
```

Then look at your database and see if the data is available. Your entries should be available in the `rainlab_translate_indexes` table. Is your data in there? Maybe you need to resave your plugin data to get it inserted there since you added the `index` property afterwards.

**Comment by BesoKakulia** [comment]
I re saved plugin data and  dd() returns
array:1 [▼
  0 => array:3 [▼
    "query" => "select `respo_newsevents_`.* from `respo_newsevents_` left join `rainlab_translate_indexes` on respo_newsevents_.id = `rainlab_translate_indexes`.`model_id` and `rainlab_translate_indexes`.`model_type` = ? and `rainlab_translate_indexes`.`locale` = ? where (`respo_newsevents_`.`title` = ? or (`rainlab_translate_indexes`.`item` = ? and `rainlab_translate_indexes`.`value` = ?)) or `description` like ?"
    "bindings" => array:6 [▼
      0 => "Respo\NewsEvents\Models\Event"
      1 => "%dino%"
      2 => "like"
      3 => "title"
      4 => "like"
      5 => "%dino%"
    ]
    "time" => 0.67
  ]
]

but search result stays same

**Comment by tobias-kuendig** [comment]
Whats in your rainlab_translate_indexes table?

**Comment by BesoKakulia** [comment]
![untitled](https://cloud.githubusercontent.com/assets/26166174/26582209/55621d42-4551-11e7-8579-3dcfa20e398a.png)

**Comment by tobias-kuendig** [comment]
Have a look at the Rainlab.Translate documentation for `transWhere` you are using it wrong:
https://github.com/rainlab/translate-plugin#indexed-attributes

[`transWhere`](https://github.com/rainlab/translate-plugin/blob/7cec25aaa2c0b6e8acf7298fea3f36115d43fa6c/behaviors/TranslatableModel.php#L32) only accepts an index and value. You cannot specify a LIKE operator.
You'll have to build the query yourself. This problem has nothing to do with the SiteSearch plugin.

**Comment by BesoKakulia** [comment]
Oky, thank you for help.

**Comment by Inklementia** [comment]
I have totally same problem, I just can't figure out how to make this work. 
        $items = Models\Record
            ::transWhere('name', "${query}")
            ->orWhere('content', 'like', "%${query}%")
            ->get();
dd() gives needed query but search results are empty

**Comment by tobias-kuendig** [comment]
Try to query the `rainlab_translate_attributes` table directly as it is done in the RainLab.Blog provider:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabBlogResultsProvider.php#L135

`transWhere` is a query scope that essentially adds a `JOIN` to your query. So you cannot combine it with `orWhere` and other conditionals.
