### ISSUE TITLE
Add Custom Provider

### ISSUE THREAD

**Issue by AugmentBLU** [OFFLINE-GmbH/oc-site-search-plugin#41]
Hello,

I have a custom plugin that is loosely based on the Rainlab Blog plugin, rather than use the boot method to extend the search plugin, I wondered how we add custom providers - without them being lost on updates?

I created a custom provider, it works great but I don't want to lose it when the search plugin requires an update. 

The reason I want a custom provider is due to my plugins using Translate and it seems a bit more straight forward copying what you already have.

Thanks!

**Comment by tobias-kuendig** [comment]
This is currently not possible. Maybe it's worth considering this functionality for a future release.

What problems do you currently have using the boot method? Translations shouldn't be much more complicated in the boot method than in a separate provider. See #40 for some inputs on this topic.

**Comment by AugmentBLU** [comment]
I need quite a bit of control over the search, due to the extra level of complexity that translations bring it makes more sense to use a dedicated provider class. 

If you can think of a way to allow for custom provider files to be included, that would really be awesome. I have quite a few plugins that will require this so it would be great if we could have a simple method to include providers.

**Comment by tobias-kuendig** [comment]
I have added support for custom result providers in version 1.2.32 currently available via edge updates. I will release this version in the beginning of next week. Until then you can test it via edge updates. 

For a usage example see the [updated README](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/README.md#advanced-method).

**Comment by AugmentBLU** [comment]
Awesome! It works really well for individual providers, however I am having an issue with using multiple in a single plugin.

```
Type error: Argument 1 passed to OFFLINE\SiteSearch\Classes\SearchService::OFFLINE\SiteSearch\Classes\{closure}() must be an instance of OFFLINE\SiteSearch\Classes\Providers\ResultsProvider, array given
```

My plugin has the following boot event

```
\Event::listen('offline.sitesearch.extend', function () {
            return [new AbcResultsProvider(), new XyzResultsProvider()];
        });
```

**Comment by tobias-kuendig** [comment]
Thank you for your report. This is fixed in the latest pre-release.

**Comment by tobias-kuendig** [comment]
These changes have now been released on the stable release channel.

**Comment by AugmentBLU** [comment]
Thanks for extending this already super helpful plugin!
