### ISSUE TITLE
Autocomplete No Result Not Working

### ISSUE THREAD

**Issue by AugmentBLU** [OFFLINE-GmbH/oc-site-search-plugin#42]
Hello,

Autocomplete returns data even if there's no results - which means the 'no results' message will not display.

If you add the following to the `Searchinput.php` file, it works. Maybe there's a more elegant way to do this but I needed a quick fix.

```
if (!$results->isEmpty())
{
     $this->setVar('results', $results);
}
```

**Comment by tobias-kuendig** [comment]
Thanks for your report. You can use `{% if results.count %}` in your `autocomplete.htm`.

This bug is fixed in Version `1.3.2`.
