### ISSUE TITLE
Request: Can you provide results for search phrases?

### ISSUE THREAD

**Issue by rangrage** [OFFLINE-GmbH/oc-site-search-plugin#43]
Hi, 

This plugin works perfectly with single word search. Is it possible to provide results for search phrases as well? 

> e.g. two bedroom flat for sale in London => "For Sale: [Two Bedroom Flat], Whitechappel, [London]"

Thanks.

**Comment by tobias-kuendig** [comment]
What results are returned is defined by the implementation of the result provider classes, see https://github.com/OFFLINE-GmbH/oc-site-search-plugin/tree/develop/classes/providers

Currently most providers simply do a `LIKE` query. What your are looking for is fulltext search (`MATCH / AGAINST` queries). If you search through your own contents there's nothing preventing you from creating such a query yourself. If you are using an existing plugin feel free to create a PR that extends this functionality.

With the release of October's Build 420 we will try to implement Laravel Scout to search the contents and use the swappable search drivers it provides.

**Comment by rangrage** [comment]
Thank you for the quick reply. 

For now I am using it with the rainlab static pages and blog plugins, and have it on all of the websites I build. 

I think Laravel Scout will be the solution I'm after.

**Comment by tobias-kuendig** [comment]
Closing this issue due to inactiviy. Simpmly reply in case your problem is not resolved.
