### ISSUE TITLE
Letters Ё and Е in Russian

### ISSUE THREAD

**Issue by zooks** [OFFLINE-GmbH/oc-site-search-plugin#44]
Please make ```е``` letter equivalent to ```ё``` in search results (and its capitalized versions ```Е``` & ```Ё```).
These letters are different, but we often use ```е``` instead of ```ё```.

So for example if I'm searching for ```елка```, search results should contain:
```елка``` and ```ёлка```.

When I'm searching for ```ёлка```, the results also should be:
```елка``` and ```ёлка```.

**Comment by graker** [comment]
Check out these results:

https://graker.ru/search?q=%D1%91%D0%B6%D0%B8%D0%BA
https://graker.ru/search?q=%D0%B5%D0%B6%D0%B8%D0%BA

There are some troubles with highlighting but there are the same results in both cases.

**Comment by zooks** [comment]
I store mostly ```ё``` letters in the database. The problem is in the different OS that use different spelling.
For example iOS always make ```Ё``` spelling autocorrection. Android, Windows and Linux don't change typed text.

**Comment by graker** [comment]
Well it seems that at least with MySQL on my server the search query doesn't make a difference between these letters (see samples above). The only issue I see is highlighting which is performed on the PHP side.

**Comment by zooks** [comment]
I don't use database. These results are from Static Pages plugin.

**Comment by graker** [comment]
Then it might be easier to either change `е` to `ё` when query is being posted, or to make a small filter replacing `ё` with `е` in content using `markdown.parse` event (if you're using markdown for static pages).

**Comment by zooks** [comment]
The problem is not in the content. As I said, using different OS causes different search results.

**Comment by graker** [comment]
Yes, I understand that, different OSes provide different letter suggestions/replacements. The point is aside from changing the plugin (which could be quite a task in this matter), you can try to adjust either search query on the fly or the content when it's being saved. It seems like a hack, but trying to implement it in the search provider for Static Pages could be even worse in my opinion.

**Comment by tobias-kuendig** [comment]
I don't think the plugin should handle such language specific edge cases but I see the need to modify the user's query before searching. If you update to version 1.3.5 you can now use `forceQuery` to overwrite the user's query with your own. 
Check out the [README](https://github.com/OFFLINE-GmbH/oc-site-search-plugin#modify-the-query-before-searching) for an example on how this might be implemented.

If you still need more sophisticated search methods I suggest you look into something index based (MySQL fulltext search, ElasticSearch, etc.).
