### ISSUE TITLE
Rainlab Blog incorrect hyperlinks help

### ISSUE THREAD

**Issue by bradgillap** [OFFLINE-GmbH/oc-site-search-plugin#45]
My blog structure uses /guide/post/post1-test

The search only returns

/blog/post/post1-test

How do I change the results to replace guide and blog?

**Comment by tobias-kuendig** [comment]
Did you select the blog page in the SiteSearch backend settings?

**Comment by bradgillap** [comment]
Sorry, I missed the backend settings completely.

**Comment by tobias-kuendig** [comment]
Did you select the blog page in the SiteSearch backend settings?
