### ISSUE TITLE
Add support for Translate plugin

### ISSUE THREAD

**Issue by tobias-kuendig** [OFFLINE-GmbH/oc-site-search-plugin#5]

**Comment by tobias-kuendig** [comment]
Support added in [v1.1.0](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/releases/tag/v1.1.0)

**Comment by iSaadSalman** [comment]
Hi. Thanks for the awesome plugin.

How can I search for language attribute so that result matches the language its switched on?

**Comment by tobias-kuendig** [comment]
What contents are you searching for? Your own custom plugin's contents or the contents from a built in one?

**Comment by iSaadSalman** [comment]
My custom plugin. Some of the fields in my plugins are translatable. How can I search against those fields when the language is switched?

Thanks,

**Comment by tobias-kuendig** [comment]
You'll have to use a [`transWhere()`](https://github.com/OFFLINE-GmbH/oc-snipcartshop-plugin/blob/develop/components/Categories.php#L95)  and [define an index](https://github.com/OFFLINE-GmbH/oc-snipcartshop-plugin/blob/develop/models/Category.php#L17) for every column you want to be searchable.

Have a look a the Rainlab.Translatable plugin for further details.

**Comment by iSaadSalman** [comment]
Ahan. I will investigate further. Thanks for your help.
