### ISSUE TITLE
Issue when creating 2 blogs in ProBlog

### ISSUE THREAD

**Issue by grafxflow** [OFFLINE-GmbH/oc-site-search-plugin#50]
There is an issue if you choose to create more than 2 blogs in ProBlog.

```
Managing Multiple Blogs

You can have multiple blogs with ProBlog. Each blog section would serve as a given posts "parent" page. Each blog with their own BlogList component.

So you might have the following:

/blog
/news
```

Maybe change the following - classes/providers/RadiantWebProBlogResultsProvider.php
Also added detection of category slug https://github.com/OFFLINE-GmbH/oc-site-search-plugin/issues/49. Unsure if this will affect older versions of ProBlog plugin? Is there a way of detecting the plugin version and update accordingly?

REF: In admin the 'Parent Blog Page' option = $post->parent column on the database.

```
/**
     * Generates the url to a blog post.
     *
     * @param $post
     *
     * @return string
     */
    protected function getUrl($post)
    {
        $langPrefix = $this->translator ? $this->translator->getLocale() : '';
		
		// Detect blog post slug set
		if(isset($post->categories->slug))
		{
			// $post->parent relates to actual blog i.e. '/blog/' '/tutorials/' etc
			return implode('/', [$langPrefix, $post->parent, $post->categories->slug, $post->slug]);
		}
    }
```

**Comment by grafxflow** [comment]
UPDATE: Regarding the category slug issue. 

The problem relates to when creating a post in ProBlog by default the 'Taxonomy' ->'Select a Category this post belongs to' is empty and is not classed as a requirement. 

So somebody could create and publish a post without allocating a category and it will stop it from working. Unlikely but use it as a fall back plan.

```
// Detect blog post slug set
if(isset($post->categories->slug))
{...
```

**Comment by tobias-kuendig** [comment]
Would you mind testing the latest Version 1.3.6 (available via Edge updates) or patch your installation manually and test these changes: ad8c248452ef6057e24248dc4a530df039901935

I don't have an up to date version of ProBlog available. This new method respects the `parent` attribute of a blog post and falls back to ProBlog's default rendering page if nothing is specified.
This way multiple blogs should no longer be a problem.

**Comment by grafxflow** [comment]
Okay I will do and I will get back to you.

**Comment by grafxflow** [comment]
I think minor tweak required.

```
if (ProBlogSettings::get('markdownMode')) {...
```


```
/**
     * Get the post's excerpt if available
     * otherwise fall back to a limited content string.
     *
     * @param $post
     *
     * @return string
     */
    private function getSummary($post)
    {
        $excerpt = $post->excerpt;
        if (mb_strlen(trim($excerpt))) {
            return $excerpt;
        }

        $content = $post->content;
        if (ProBlogSettings::get('markdownMode')) {
            $content = Post::formatHtml($content);
        }

        return $content;
    }
```

**Comment by tobias-kuendig** [comment]
Thanks, I missed that. Everything else is working as expected?

**Comment by grafxflow** [comment]
Yes works fine.

Using:
ProBlog v5.0.3
October CMS build v433

**Comment by tobias-kuendig** [comment]
Great, thanks for your help! I'm releasing this as 1.3.6.

**Comment by grafxflow** [comment]
👍
