### ISSUE TITLE
->orderBy('published_at', 'desc')

### ISSUE THREAD

**Issue by grafxflow** [OFFLINE-GmbH/oc-site-search-plugin#52]
Just enquiring when doing an ajax autosearch input. The results seem not to be ordering by published_at.

Is it based more on the results title, content etc where the value is found (relevance)?

Here is the raw query that is output ($posts->toSql())...

```
select * from `octobercms_radiantweb_blog_posts` 
where `published` is not null 
and `published` = `1` 
and (`title` like `%searchvalue%` 
or `content` like `%searchvalue%` 
or `excerpt` like `%searchvalue%`) 
order by `published_at` desc
```

When I do this query direct to the database the results are correct.

**Comment by tobias-kuendig** [comment]
Thank you for reporting this issue. Since all results are sorted by the `relevance` property the order by statement is useless.

Starting from version `1.3.7` there is the ability to add age penalties to search results. The RainLab.Blog and RadiantWeb.ProBlog plugins will make use of this feature.
