### ISSUE TITLE
Support for custom plugin not working

### ISSUE THREAD

**Issue by LarBearrr** [OFFLINE-GmbH/oc-site-search-plugin#53]
Expected behavior:
Extended search will look at model for custom plugin.

Actual behavior:
After adding an Event listener in my plugin's boot function, the results are not added.

I followed the instructions but am not showing any results from my plugin's model.

**Comment by tobias-kuendig** [comment]
Without code examples I'm not able to help you. Please post your event listener. 

Do you see the `Event triggered` message if you use this listener?

```php
\Event::listen('offline.sitesearch.query', function ($query) {
    dd('Event triggered');
});
```

**Comment by WWRFresource** [comment]
Thanks for the reply. I didnt provide a specific example because I basically followed the instructions in the repository, except I used a different model. Here is what I tried though:

```
        \Event::listen('offline.sitesearch.query', function ($query) {

            // Search your plugin's contents
            $items = \Wwrf\TransitionCenter\Models\TempService::where('name', 'like', "%${query}%")->get();
    
            // Now build a results array
            $results = $items->map(function ($item) use ($query) {
    
                // If the query is found in the title, set a relevance of 2
                $relevance = mb_stripos($item->name, $query) !== false ? 2 : 1;
                
                // Optional: Add an age penalty to older results. This makes sure that
                // never results are listed first.
                // if ($relevance > 1 && $item->published_at) {
                //     $relevance -= $this->getAgePenalty($item->published_at->diffInDays(Carbon::now()));
                // }
    
                return [
                    'name'     => $item->name,
                    'comments'      => $item->comment,
                    'url'       => '/tempservice/' . $item->slug,
                    'relevance' => $relevance, // higher relevance results in a                               higher position in the                                      results listing
                    // 'meta' => 'data',       // optional, any other                                         information you want
                                               // to associate with this result
                    // 'model' => $item,       // optional, pass along the                                    original model
                ];
            });
    
            return [
                'provider' => 'Temp Service', // The badge to display for this result
                'results'  => $results,
            ];
        });
```

Now concerning your suggestion, I removed my code and added your snippet. When I begin the search I am presented with an alert box containing some script:
![image](https://user-images.githubusercontent.com/28734844/38379633-e47eb08a-38c6-11e8-87e7-732143fadeb0.png)

However, if I close the alert and press the search button, I do see the 'Event triggered' message:
![image](https://user-images.githubusercontent.com/28734844/38379791-731bba18-38c7-11e8-9b9a-621509125728.png)


I want to mention also that if I use my code, the alert box does not show. Thanks again for your quick reply. I'm enjoying the autocomplete feature you implemented and the overall functionality, and I hope to be able to search my own models as well.

**Comment by tobias-kuendig** [comment]
And what does `dd($items);` return after you fetch them? Any results in there?

**Comment by WWRFresource** [comment]
dd($items) dumps the following:

```
Collection {#1432 ▼
  #items: array:1 [▼
    0 => TempService {#1433 ▼
      #dates: array:1 [▶]
      #jsonable: array:1 [▶]
      +rules: []
      +table: "wwrf_transitioncenter_tempservices"
      +implement: null
      +attributes: array:13 [▼
        "id" => 19
        "name" => "Randstad at Johnson Controls"
        "address" => "3120 N Mead St."
        "phone" => "0"
        "website" => "http://randstadusa.com"
        "type_of_work" => "["DL","TA","TH","DH"]"
        "accept_felonies" => "Yes."
        "rejected_felonies" => "Aggravated charges within the last 7 years."
        "employment_type" => "Manufacturing/Logistics"
        "comments" => "Apply online. Only 1 Drug felony w/in the last 7 years. Older crimes may be ok."
        "created_at" => "2018-02-19 11:12:22"
        "updated_at" => "2018-04-05 18:12:17"
        "deleted_at" => null
      ]
```

So my query is working. I went ahead and worked a little bit forward and did a dd($results) and got the following:

```
Collection {#1418 ▼
  #items: array:1 [▼
    0 => array:4 [▼
      "name" => "Randstad at Johnson Controls"
      "text" => "Apply online. Only 1 Drug felony w/in the last 7 years. Older crimes may be ok."
      "url" => "/tempservice/19"
      "relevance" => 2
    ]
  ]
}
```

Now if I remove the dd()'s and just perform my search, neither the item nor the result are displayed in the autocomplete box or my results page.

**Comment by tobias-kuendig** [comment]
It's hard to help you any further but you should be able to debug the problem yourself.

I'd start here and check if your results are included in the collection:
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/SearchService.php#L115

Also try to access all results in your partial to see if they are there `{{ siteSearch.resultCollection }}`.

**Comment by LarBearrr** [comment]
@tobias-kuendig I'm going to close this issue as it is old and I'm not longer working on the project that implemented the plugin. Thanks for your help, and for octobertricks.com!
