### ISSUE TITLE
Search results URL not working

### ISSUE THREAD

**Issue by LarBearrr** [OFFLINE-GmbH/oc-site-search-plugin#55]
The URLs for my search results are not being created properly.

On localhost, they are missing the directory my development files are in... for example:

URLs are showing as (see below): http://localhost/posts/post-slug
![image](https://user-images.githubusercontent.com/28734844/38586992-8ac592de-3ce5-11e8-9f88-7e4efc542a6f.png)

They should be showing as: http://localhost/mysite/posts/post-slug

This is causing 'Page not found' errors to result from clicking on the results.

UPDATE:

On my production server, the autocomplete results are not showing anything related to the job post. In fact, they link back to the search result page:
![image](https://user-images.githubusercontent.com/28734844/38588071-8ccf5aa2-3ce9-11e8-8846-497da1519401.png)

Also, here is my code/directory structure:

theme/layouts/default.htm:

[searchInput]
useAutoComplete = 1
autoCompleteResultCount = 5
showProviderBadge = 1
searchPage = "jobs/search.htm"

theme/pages/default.htm:
```
<form action="{{ searchInput.searchPage | page }}?q={{ query | url_encode(true) }}" method="GET" class="form-inline my-2 my-lg-0 ml-auto">
    <div class="ss-search-form">
        <div class="ss-search-form__input">
            <input name="q" type="text" placeholder="What are you looking for?" autocomplete="on"
                    {% if searchInput.useAutoComplete %}
                        data-track-input
                        data-request="onType"
                        data-request-before-update="document.getElementById('autocomplete-results').classList.add('ss-search-form__results--visible')"
                        data-request-update="'{{ searchInput }}::autocomplete': '#autocomplete-results'"
                    {% endif %} />
            <button class="btn btn-outline-white btn-md my-2 my-sm-0 ml-3 ss-search-form__submit" type="submit">Search</button>
        </div>
        <div class="ss-search-form__results white z-depth-2" id="autocomplete-results"></div>
    </div>
</form>
```

themes/pages/jobs/search.htm:
```
[searchResults]
resultsPerPage = 10
showProviderBadge = 1
noResultsMessage = "Your search did not return any results."
visitPageMessage = "Visit page"
==
<h2>Search results for {{ searchResults.query }}</h2>
{% component 'searchResults' %}
```

**Comment by tobias-kuendig** [comment]
It looks like you have created the search results via your own plugin?

Make sure to build the URL using the CMS Controller class so your APP_URL is respected:
https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/OfflineSnipcartShopResultsProvider.php#L91

**Comment by WWRFresource** [comment]
Missed a very basic and important step when I pushed to production... neglected to specify the blog post page in the settings page... 😊 
URLs are working now with one minor hiccup.. perhaps you can help here and I should be done pestering you:

I needed to add a custom method to my results links because I track when users click these links on our page. I went ahead and copied over the component partials to my theme directory so I could add what I needed. My results page is functioning properly; however, the autocomplete results do not seem to be displaying properly:

theme/partials/searchInput/content.htm:

```
<h4 class="ss-autocomplete-result__title">
    {% if user %}
        <a href="{{ result.url }}" data-request="onView" data-request-data="id: {{ result.id }}">
            {{ result.title | raw }}
        </a>
    {% else %}
        <a href="{{ result.url }}">{{ result.title | raw }}</a>
    {% endif %}
...
</h4>
```

Inspecting the autocomplete results shows this:
![image](https://user-images.githubusercontent.com/28734844/38622157-2edb8fea-3d68-11e8-9b65-6cfe12081cec.png)

What's confusing me is that I have the same code in my searchResult content.htm partial and it is working fine.

**Comment by tobias-kuendig** [comment]
Does your component have an alias or is it called `searchInput`? Are you able to override the `default.htm` partial of the `searchInput` component?

**Comment by WWRFresource** [comment]
The component is called searchInput and it is placed in my layout file as such:
```
[searchInput]
useAutoComplete = 1
autoCompleteResultCount = 5
showProviderBadge = 1
searchPage = "jobs/search.htm"
```

Here's what I've found so far. It seems like I am not able to access the Session component from the RainLab User plugin on these partials, for whatever reason.

For instance, if I just try to show the user id in the partial with {{ user.id }} nothing shows up. I took out the Twig if statement and hard coded the method into the URL:

```
<h5 class="h5-responsive ss-autocomplete-result__title">
    <a href="{{ result.url }}" data-request="onViewJob" data-request-data="job_id: {{ result.id }}">
        {{ result.title | raw }} {{ user.id }}
    </a>
</h5>
{% if __SELF__.showProviderBadge %}
    <span class="ss-autocomplete-result__badge badge red">
        {{ result.provider }}
    </span>
{% endif %}
```

This works just fine. When I add the if statement, it breaks.

**Comment by tobias-kuendig** [comment]
Is the `session` component on your page or layout? Try putting it on the layout. Also try to access the user property with `session.user` maybe that works better.

**Comment by WWRFresource** [comment]
Just to clarify, my Session component is in the layout as well. Your suggestion to try session.user is interesting as this seems to have fixed the problem. I just wonder what is allowing me to access user.id from the searchResult component and not searchInput.

theme/partials/searchInput/content.htm:
```
<h5 class="h5-responsive ss-autocomplete-result__title">
    <a href="{{ result.url }}" 
         {% if session.user.groups.first.name == 'Users' %}
         data-request="onViewJob" data-request-data="job_id: {{ result.id }}"
         {% endif %}>
        {{ result.title | raw }} {{ user.id }}
    </a>
</h5>
{% if __SELF__.showProviderBadge %}
    <span class="ss-autocomplete-result__badge badge red">
        {{ result.provider }}
    </span>
{% endif %}
```
![image](https://user-images.githubusercontent.com/28734844/38628311-ad8cb090-3d76-11e8-8e8c-4486411f9d76.png)
![image](https://user-images.githubusercontent.com/28734844/38628318-b386d3c2-3d76-11e8-844d-45457a8526ab.png)

**Comment by tobias-kuendig** [comment]
Hmm, maybe it has to do with the ajax request? Can you access the user
variable in the default partial? Otherwise it's maybe a minor difference in
the structure of both compontents. --

--
Freundliche Grüsse
Tobias Kündig

*OFFLINE* GmbH
Winkelriedstrasse 53
6003 Luzern
Schweiz

tobias@offline.swiss
https://offline.swiss
+41 (0)41 260 30 39

**Comment by FlorinMarina** [comment]
I have the same issue 

Blog URL
`http://blog.test/reviews-io-2018-development-and-expansion`

Dump Url from result object 

![image](https://user-images.githubusercontent.com/40028310/54045325-fa074580-41d9-11e9-8934-2f236f721555.png)

**Comment by FlorinMarina** [comment]
I found the issue ... I consider this a Bug

In RainlabBlogResultsProvider
    ```
protected function getUrl($post)
    {
        $url = trim(Settings::get('rainlab_blog_posturl', '/blog/post'), '/');

        return implode('/', [$url, $post->slug]);
    }
```

**Comment by LarBearrr** [comment]
Been a while since I have worked on this project. I believe I figured out the issue but can't remember exactly what it was, even after reading over my original comments. 

Glad this helped you somewhat!

**Comment by FlorinMarina** [comment]
I will come up with the solution in a bitt

**Comment by tobias-kuendig** [comment]
@FlorinMarina this is a legacy method that is not actively in use anymore. You should set the `rainlab_blog_page` setting via the backend settings. Then the URL is generated using a the controller and RainLab.Blog's setUrl method:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabBlogResultsProvider.php#L64

https://github.com/rainlab/blog-plugin/blob/99bc8fc0efab5203e2d353dacaf2a05f2618bf5b/models/Post.php#L146

**Comment by FlorinMarina** [comment]
Cheers.

![image](https://user-images.githubusercontent.com/40028310/54047281-5456d500-41df-11e9-9810-6ae9cf92af2b.png)

**Comment by LarBearrr** [comment]
Closing as this is old and I'm no longer on the project anymore. See #53.
