### ISSUE TITLE
Support with rainlab.translate attributes ?

### ISSUE THREAD

**Issue by HugoLachance** [OFFLINE-GmbH/oc-site-search-plugin#58]
Hi,

On the plugin description page, it's written that Multilingual contents via RainLab.Translate are supported.

Does this include the contents of the attribute_data field of the rainlab_translate_attributes table?

Because there is translated content in this table, but it is in JSON format.

Does the plugin can search the contents of this table ?
Is there special config that we need to implement to make it happen ?

Thanks !

**Comment by tobias-kuendig** [comment]
Hi

The RainLab.Translate support means primarily that url generation for search results will respect the currently active locale. There are also some search providers that will search contents in the currently active lcoale, like Rainlab.Blog.

You can see here how this is implemented:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabBlogResultsProvider.php#L124

It will search the `attribute_data` field. Are you looking for support for a specific plugin?

**Comment by tobias-kuendig** [comment]
Closing this issue due to inactiviy. Simpmly reply in case your problem is not resolved.
