### ISSUE TITLE
AJAX Form support?

### ISSUE THREAD

**Issue by jan-vince** [OFFLINE-GmbH/oc-site-search-plugin#59]
Hi, I haven't found a way to use search form with AJAX to update search results without page refresh.

Is this possible?

**Comment by tobias-kuendig** [comment]
Not out of the box. But it is fairly trivial to create a custom component that listens for your AJAX query.

You can then use the `SearchService` class to gather all results and render them any way you want.

See https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/components/SearchResults.php#L166 for a working example.

**Comment by jan-vince** [comment]
Thank you, I will try it!
