### ISSUE TITLE
Class name is not registered for the component "searchInput".

### ISSUE THREAD

**Issue by pikanji** [OFFLINE-GmbH/oc-site-search-plugin#63]
I got this error message in the title after I install oc-site-search-plugin via composer.
```
"require": {
    ...
    "offline/oc-site-search-plugin": "~1.3",
    ...
},
```
This installs the package to `plugins/offline/site-search` directory.

When I change the directory name to `plugins/offline/sitesearch`, the error does not appear.

I think this can be solved by changing the package name in `oc-site-search-plugin/composer.json`.
Or am I doing something wrong?

**Comment by tobias-kuendig** [comment]
This is fixed in version 1.3.10. Thank you for the bug report 👍
