### ISSUE TITLE
Rainlab Pages search provider ignores placeholders

### ISSUE THREAD

**Issue by Rike-cz** [OFFLINE-GmbH/oc-site-search-plugin#67]
I discovered that Rainlab Pages search provider ignores placeholders. I think that `{% put ... %}` tag contains text, which is part of page, it is differently processed by layout only. Do you agree?

**Comment by tobias-kuendig** [comment]
Depending on your use of the placeholders this could be a problem, yes.

We can only search through what is saved on disk. If your placeholder changes something dynamically when the page is rendered there is no viable method to search through these generated contents.

**Comment by Rike-cz** [comment]
`{% put ... %}` tag is also saved on disk in the same file. My static page looks like:
```
[viewBag]
...
==
{% put summary %}
<p>These keywords I want in search result too...</p>
{% endput %}
==
<p>These keywords are in search result now.</p>
```
I think problem is [this line](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabPagesResultsProvider.php#L61), because `$page->parsedMarkup` ignores content where put-tags are placed.

**Comment by Rike-cz** [comment]
I am not so familiar with deep OctoberCMS processes, but it looks like _placeholders_ are accessible as _parsedMarkup_...
https://github.com/rainlab/pages-plugin/blob/master/classes/Page.php#L60

**Comment by tobias-kuendig** [comment]
This is fixed in 56024112f09ada5ab6b56c6d478cb2aa8d09774f and released as v1.3.14

Thank you!

**Comment by Rike-cz** [comment]
Little appendix: Placeholder cannot be a part of result excerpt, because their content is not placed to Result (https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/56024112f09ada5ab6b56c6d478cb2aa8d09774f/classes/providers/RainlabPagesResultsProvider.php#L36). But I do not know, if it's good idea...

**Comment by tobias-kuendig** [comment]
Since a placeholder may contain further code snippts it's maybe best to simply use the parsedMarkup property as excerpt.

**Comment by Rike-cz** [comment]
ok, thanks!
