### ISSUE TITLE
Search on multiple models

### ISSUE THREAD

**Issue by rvgmartins** [OFFLINE-GmbH/oc-site-search-plugin#68]
Is it possible to search on several models with different rules?

An example with actors and films is it possible to search on both?

I only find search in one model like this:

 $items = Models\Movie::where('name', 'like', "%${query}%")
                                            ->orWhere('description', 'like', "%${query}%")
                                            ->get();

**Comment by tobias-kuendig** [comment]
You mean like this?

```php
$items = Movie::where('name', 'like', "%${query}%")
              ->orWhere('description', 'like', "%${query}%")
              ->orWhereHas('actors', function($q) {
                   $q->where('name', 'like', "%${query}%");
              })
              ->get();
```

https://laravel.com/docs/5.7/eloquent-relationships#querying-relationship-existence

**Comment by rvgmartins** [comment]
Thank you so much for your answer.

This isn't what I wanted, I want to search on several unrelated models

Tobias Kündig <notifications@github.com> escreveu no dia segunda,
11/02/2019 à(s) 06:13:

**Comment by tobias-kuendig** [comment]
The results array you return can contain any type of model you want. Just search what you need and append it to the `$results` array.

```
return [
    'provider' => 'ModelAandBResults',
    'results'  => array_merge($resultsModelA, $resultsModelB),
];
```
