### ISSUE TITLE
Is there a way to AJAXify search results ?

### ISSUE THREAD

**Issue by Nvironmental** [OFFLINE-GmbH/oc-site-search-plugin#69]

**Comment by tobias-kuendig** [comment]
Could you be a bit more specific with your question? It's hard to help you with your request without any more information on what you are trying to achieve.

Thank you

**Comment by Nvironmental** [comment]
My sincere apologies, 

I am working on a website which also uses PhotoAlbums Plugin. In Fig 1, you can see a search button, which upon clicking, slides in a search modal - see Fig 2. 
I was wondering if there is a way you could guide me, where the user would type the search query in the input field and it would populate the results below (see Fig 3) without refreshing/redirecting the page.

Thanks 
![fig 1](https://user-images.githubusercontent.com/31243747/52896431-c72aec80-31ed-11e9-9ac9-a77086fefcf3.png)
![fig 2](https://user-images.githubusercontent.com/31243747/52896432-c72aec80-31ed-11e9-9929-62dce36c693a.png)
![fig 3](https://user-images.githubusercontent.com/31243747/52896433-c7c38300-31ed-11e9-833e-93144ac5ce3a.png)

**Comment by tobias-kuendig** [comment]
No worries! Did you see the [searchInput](https://github.com/OFFLINE-GmbH/oc-site-search-plugin#searchinput) component with the `useAutoComplete` option? This will return results as soon as the user begins to type. By overwriting the results partial of the component you should be able to achieve exactly what you want.

**Comment by tobias-kuendig** [comment]
Closing this issue due to inactiviy. Simpmly reply in case your problem is not resolved.
