### ISSUE TITLE
Searching for blog categories returns no results

### ISSUE THREAD

**Issue by willstocks-tech** [OFFLINE-GmbH/oc-site-search-plugin#70]
Hi guys,

I have installed the plugin and set it up, however if I search for a blog category (for example: https://code.willstocks.co.uk/category/guides - using the search term: guide), no search results are returned.

Is there a way for me to include categories into search results? I have enabled the "CMS Pages" option and added `[siteSearchInclude]` to the page, which results in:

```
title = "Blog Category"
url = "/category/:slug/:page?"
layout = "generic"
is_hidden = 0

[blogPosts]
pageNumber = "{{ :page }}"
categoryFilter = "{{ :slug }}"
postsPerPage = 10
noPostsMessage = "No posts found"
sortOrder = "published_at desc"
categoryPage = "blog-category"
postPage = "blog-post"

[siteSearchInclude]
```

**Comment by tobias-kuendig** [comment]
This is not how the cms pages provider works. The cms provider will only search the literal text on your page.htm file ‒ it cannot search the content that October generates on the page.

If you want to make your categories searchable you'll have to register your own results provider and return custom results as described here:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin#simple-method

**Comment by willstocks-tech** [comment]
Thanks @tobias-kuendig - I will have a further read to see if I can implement something! I'm new to October!
