### ISSUE TITLE
Support for Builder and Small Records

### ISSUE THREAD

**Issue by exaline-ru** [OFFLINE-GmbH/oc-site-search-plugin#76]
You have a great plugin. Can you can add support (or instructions) to: The Builder (11670 installations) and Small Records (398 installations)!? All Records have a general view:/record/:record... Thank you in advance.

**Comment by exaline-ru** [comment]
The issue has already been resolved.

**Comment by Inklementia** [comment]
> The issue has already been resolved.

How?)

**Comment by tobias-kuendig** [comment]
Builder and Small Records both are used to generate custom content types. You can add support to search those as documented in the README:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin#add-support-for-custom-plugin-contents

**Comment by Inklementia** [comment]
Thanks, takes time to figure things out

**Comment by Inklementia** [comment]
How to get featured image from post with Small Record and search for custom content types

'thumb'     => optional($item->images)->first() - this one gets 1st image from images array but not featured image

**Comment by Inklementia** [comment]
and using Small Records I cant make search multilingual, it searches just default language. Although Small Records have multilang support and all fields are translatable

**Comment by tobias-kuendig** [comment]
You should check the small records documentation on how to get the featured image. I don't know the plugin well and can't help you.

Searching through translated contents is a bit tricky. The default Rainlab.Blog provider handles this for the Blog posts. You might be able to adopt it for your plugin:

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/classes/providers/RainlabBlogResultsProvider.php#L94
