### ISSUE TITLE
Call to a member function getFileName() on null

### ISSUE THREAD

**Issue by skobb** [OFFLINE-GmbH/oc-site-search-plugin#77]
I' m using Mall and sitesearch together, and if i type non-existing product, all going ok, i've been redirected to searchresult page where "no results" is written. But if try to type existing product, I have an error "Call to a member function getFileName() on null"
some logs:
![image](https://user-images.githubusercontent.com/46927994/56120423-bb05a600-5f76-11e9-98db-f0ecdfb50627.png)
Help me please, I know I made something wrong.

**Comment by tobias-kuendig** [comment]
Did you select the right pages in the backend settings of mall?

https://offline-gmbh.github.io/oc-mall-plugin/getting-started/installation.html#pages

**Comment by skobb** [comment]
> Did you select the right pages in the backend settings of mall?
> 
> https://offline-gmbh.github.io/oc-mall-plugin/getting-started/installation.html#pages

No, I didn't. Thank You!

**Comment by tobias-kuendig** [comment]
Great! :+1:
