### ISSUE TITLE
[Bug] Throws error when searching for empty string

### ISSUE THREAD

**Issue by JayFrogster** [OFFLINE-GmbH/oc-site-search-plugin#79]
When Ajax onType is enabled and you enter an empty string via hitting the space bar - the search provider script (in my case for Rainlab.Blog) is throwing an error because `mb_strpos()` does not allow an empty delimiter.

**Comment by tobias-kuendig** [comment]
Thank you for this bug report! The issue has been fixed in v1.3.22.
