### ISSUE TITLE
Return meta_title as result for class RainlabPages

### ISSUE THREAD

**Issue by Wachem** [OFFLINE-GmbH/oc-site-search-plugin#86]
If meta_title is present in viewbag, use it as title. For example:

`$title = isset($page->viewBag['title']) ? $page->viewBag['title'] : '';`
`$title = isset($page->viewBag['meta_title']) ? $page->viewBag['meta_title'] : $title;`
`$relevance = $this->containsQuery($title) ? 2 : 1;`

**Comment by tobias-kuendig** [comment]
Fixed in a27234e, thanks for your input @Wachem!
