### ISSUE TITLE
Is the plugin Documents available

### ISSUE THREAD

**Issue by janvandelaar** [OFFLINE-GmbH/oc-site-search-plugin#90]
Hi
I can't get is to work in my own plugin called Documents. Is it possible to download the plugin somewhere so that I can have a look at it. I keep getting the error stating there is no class called Document.

**Comment by tobias-kuendig** [comment]
Just show some code, I'm sure we can find the issue.

**Comment by janvandelaar** [comment]
I have this in my plugin.php

`<?php namespace JanVanDeLaar\Documents;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

public function boot()
{
    \Event::listen('offline.sitesearch.query', function ($query) {

        // Search your plugin's contents
        $items = Document::where('title', 'like', "%${query}%")
                                        ->orWhere('content', 'like', "%${query}%")
                                        ->get();

        // Now build a results array
        $results = $items->map(function ($item) use ($query) {

            // If the query is found in the title, set a relevance of 2
            $relevance = mb_stripos($item->title, $query) !== false ? 2 : 1;
            
            // Optional: Add an age penalty to older results. This makes sure that
            // newer results are listed first.
            // if ($relevance > 1 && $item->published_at) {
            //     $relevance -= $this->getAgePenalty($item->published_at->diffInDays(Carbon::now()));
            // }

            return [
                'title'     => $item->title,
                'text'      => $item->content,
                'url'       => '/document/' . $item->slug,
                'thumb'     => $item->images->first(), // Instance of System\Models\File
                'relevance' => $relevance, // higher relevance results in a higher
                                           // position in the results listing
                // 'meta' => 'data',       // optional, any other information you want
                                           // to associate with this result
                // 'model' => $item,       // optional, pass along the original model
            ];
        });

        return [
            'provider' => 'Document', // The badge to display for this result
            'results'  => $results,
        ];
    });
}
}
`

I keep getting:
"Class 'JanVanDeLaar\Documents\Document' not found" on line 20 of /mnt/web006/c1/10/56956010/htdocs/janenwim.nl/plugins/janvandelaar/documents/Plugin.php

[janvandelaar.zip](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/files/4107059/janvandelaar.zip)

This is the very basic plugin. If I get this to work I can adapt search to other plugins as well

Thank you very mutch for helping.

**Comment by tobias-kuendig** [comment]
You are missing a `use JanVanDeLaar\Documents\Models\Document` on the top of your plugin class.

**Comment by janvandelaar** [comment]
So this way it should work:
`<?php namespace JanVanDeLaar\Documents;

use JanVanDeLaar\Documents\Models\Document

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
    {
        \Event::listen('offline.sitesearch.query', function ($query) {

            // Search your plugin's contents
            $items = Document::where('title', 'like', "%${query}%")
                                            ->orWhere('content', 'like', "%${query}%")
                                            ->get();

            // Now build a results array
            $results = $items->map(function ($item) use ($query) {

                // If the query is found in the title, set a relevance of 2
                $relevance = mb_stripos($item->title, $query) !== false ? 2 : 1;
                
                // Optional: Add an age penalty to older results. This makes sure that
                // newer results are listed first.
                // if ($relevance > 1 && $item->published_at) {
                //     $relevance -= $this->getAgePenalty($item->published_at->diffInDays(Carbon::now()));
                // }

                return [
                    'title'     => $item->title,
                    'text'      => $item->content,
                    'url'       => '/document/' . $item->slug,
                    'thumb'     => $item->images->first(), // Instance of System\Models\File
                    'relevance' => $relevance, // higher relevance results in a higher
                                               // position in the results listing
                    // 'meta' => 'data',       // optional, any other information you want
                                               // to associate with this result
                    // 'model' => $item,       // optional, pass along the original model
                ];
            });

            return [
                'provider' => 'Document', // The badge to display for this result
                'results'  => $results,
            ];
        });
    }
}`

**Comment by janvandelaar** [comment]
I tried your solution but as soon as I put "use JanVanDeLaar\Documents\Models\Document" in my plugin.php the plugin is no longer visible in the backend. Can you point out where in the plugin.php your code should be places and where "use JanVanDeLaar\Documents\Models\Document" should be located? What I have right now is this:

'
<?php namespace JanVanDeLaar\Documents;

use System\Classes\PluginBase;



class Plugin extends PluginBase
{

use JanVanDeLaar\Documents\Models\Document

    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
	{
	    \Event::listen('offline.sitesearch.query', function ($query) {

	        // Search your plugin's contents
	        $items = Document::where('title', 'like', "%${query}%")
	                                        ->orWhere('content', 'like', "%${query}%")
	                                        ->get();

	        // Now build a results array
	        $results = $items->map(function ($item) use ($query) {

	            // If the query is found in the title, set a relevance of 2
	            $relevance = mb_stripos($item->title, $query) !== false ? 2 : 1;
	            
	            // Optional: Add an age penalty to older results. This makes sure that
	            // newer results are listed first.
	            // if ($relevance > 1 && $item->published_at) {
	            //     $relevance -= $this->getAgePenalty($item->published_at->diffInDays(Carbon::now()));
	            // }

	            return [
	                'title'     => $item->title,
	                'text'      => $item->content,
	                'url'       => '/document/' . $item->slug,
	                'thumb'     => $item->images->first(), // Instance of System\Models\File
	                'relevance' => $relevance, // higher relevance results in a higher
	                                           // position in the results listing
	                // 'meta' => 'data',       // optional, any other information you want
	                                           // to associate with this result
	                // 'model' => $item,       // optional, pass along the original model
	            ];
	        });

	        return [
	            'provider' => 'Document', // The badge to display for this result
	            'results'  => $results,
	        ];
	    });
	}

}

'

**Comment by janvandelaar** [comment]
I tried your solution but as soon as I put "use JanVanDeLaar\Documents\Models\Document" in my plugin.php the plugin is no longer visible in the backend. Can you point out where in the plugin.php your code should be places and where "use JanVanDeLaar\Documents\Models\Document" should be located? What I have right now is this:

`<?php namespace JanVanDeLaar\Documents;

use System\Classes\PluginBase;



class Plugin extends PluginBase
{

use JanVanDeLaar\Documents\Models\Document

    public function registerComponents()
    {
    }

    public function registerSettings()
    {
    }

    public function boot()
	{
	    \Event::listen('offline.sitesearch.query', function ($query) {

	        // Search your plugin's contents
	        $items = Document::where('title', 'like', "%${query}%")
	                                        ->orWhere('content', 'like', "%${query}%")
	                                        ->get();

	        // Now build a results array
	        $results = $items->map(function ($item) use ($query) {

	            // If the query is found in the title, set a relevance of 2
	            $relevance = mb_stripos($item->title, $query) !== false ? 2 : 1;
	            
	            // Optional: Add an age penalty to older results. This makes sure that
	            // newer results are listed first.
	            // if ($relevance > 1 && $item->published_at) {
	            //     $relevance -= $this->getAgePenalty($item->published_at->diffInDays(Carbon::now()));
	            // }

	            return [
	                'title'     => $item->title,
	                'text'      => $item->content,
	                'url'       => '/document/' . $item->slug,
	                'thumb'     => $item->images->first(), // Instance of System\Models\File
	                'relevance' => $relevance, // higher relevance results in a higher
	                                           // position in the results listing
	                // 'meta' => 'data',       // optional, any other information you want
	                                           // to associate with this result
	                // 'model' => $item,       // optional, pass along the original model
	            ];
	        });

	        return [
	            'provider' => 'Document', // The badge to display for this result
	            'results'  => $results,
	        ];
	    });
	}

}

`

**Comment by janvandelaar** [comment]
It's working prettiy nice now! Thanks!
