### ISSUE TITLE
Result Links Aren't working

### ISSUE THREAD

**Issue by Mitchbird** [OFFLINE-GmbH/oc-site-search-plugin#92]
I've managed to get the results to display properly, but I am having problems with getting the links to go to the page corresponding with the search result. How do I get the links to work?

**Comment by tobias-kuendig** [comment]
What type of results don't work (Blog, Static pages)?

Have you set the right cms pages via SiteSearch's backend settings?

**Comment by Mitchbird** [comment]
@tobias-kuendig 
That was the problem , I must've changed it. Thank you
