### ISSUE TITLE
Cant get it to searching words cotaining 'åäö'.

### ISSUE THREAD

**Issue by raktfranhjartat** [OFFLINE-GmbH/oc-site-search-plugin#93]
Can't get this plugin to search for words containing 'åäö'.

**Comment by raktfranhjartat** [comment]
Dont work when the results are jsonable in my database. Having a Field that contains ingrediens for recipes and it is saved as jsonable in my database. And cant search for anything that contains åäö. But it works when my title contains it

**Comment by tobias-kuendig** [comment]
Did you write a custom search provider? The plugin does not do the actual searching, it just collects search results of different providers.

What contents (of what plugin) are you trying to search?

**Comment by raktfranhjartat** [comment]
I am searching my own plugin so have done my own search provider. But can get it to search for åäö in my jsonable content

**Comment by tobias-kuendig** [comment]
Check your JSON contents. It's possible that the Umlauts are encoded in the JSON columns, so you cannot search for literal `ääü` characters.

Also check out MySQL's JSON_CONTAINS functions which should help you in this case.

**Comment by raktfranhjartat** [comment]
They where encoded in my json column. Dont know why i didnt see that before.

**Comment by raktfranhjartat** [comment]
Do you maybe know why it is being encoded and how to fix it?

**Comment by tobias-kuendig** [comment]
This is done by Laravel/October when storing the data in the database. 

Instead of fighting the framework, you can simply encode the value yourself and then use the `$encoded` value to query your JSON data:

```php
>>> $query = 'äöü';
=> "äöü"
>>> $encoded = json_encode($query);
=> ""\u00e4\u00f6\u00fc""
```
