### ISSUE TITLE
Result collection in autocomplete mode is not sorted by relevance

### ISSUE THREAD

**Issue by Rike-cz** [OFFLINE-GmbH/oc-site-search-plugin#97]
In `OFFLINE\SiteSearch\Classes\SearchService` are SearchProviders asked to result, but finally collection is not sorted by relevance for autocomplete in SearchInput component.
I think [there](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/components/SearchInput.php#L132) is missing code like [here](https://github.com/OFFLINE-GmbH/oc-site-search-plugin/blob/develop/components/SearchResults.php#L170-L176) is.

**Comment by tobias-kuendig** [comment]
Great find! This is fixed in https://github.com/OFFLINE-GmbH/oc-site-search-plugin/commit/f3ab046c727d4280ffc098bf2d7567d2302f3d79
